MTData.Web/Controllers/CountryStateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MTD.Core.Service.Interface;
using MTData.Web.ViewData;
using Ninject;
using System.Text;
using System.Reflection;
using System.Globalization;
using MTData.Utility;
using System.Text.RegularExpressions;

namespace MTData.Web.Controllers
{
    public class CountryStateController : Controller
    {
        readonly ILogger _logger = new Logger();
        private readonly ICommonService _commonService;
        private StringBuilder _logMessage;

        public CountryStateController([Named("CommonService")] ICommonService commonService, StringBuilder logMessage)
        {
            _commonService = commonService;
            _logMessage = logMessage;
        }
        /// <summary>
        /// Purpose             :   To get state list
        /// Function Name       :   GetStateList
        /// Created By          :   Madhuri Tanwar
        /// Created On          :   4/23/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY" 
        /// </summary>
        /// <param name="countryId"></param>
        /// <param name="mtch"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetStateList(string countryId, string mtch)
        {
            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " +
                            MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture,
                    " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("Calling GetStateList method of _commonService class to get state list for Australia");
                var stateDtoList = _commonService.GetStateList(countryId, mtch);
                _logMessage.Append("GetStateList method of _commonService executed successfully");
                _logMessage.Append("converting ToStateViewDataList list into stateList");
                var stateList = stateDtoList.ToStateViewDataList().OrderBy(s => s.Name).ToList();
                _logMessage.Append("convert stateDtoList into stateList successful");
                _logMessage.Append("returning state list");
                List<string> list = new List<string>();
                foreach (StateViewData str in stateList)
                {
                    list.Add(str.Name);
                }
                var states = list.Take(10).Distinct();
                return Json(states, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), ex);
            }
            return null;
        }

        /// <summary>
        /// Purpose             :   To get city list
        /// Function Name       :   GetCityList
        /// Created By          :   Madhuri Tanwar
        /// Created On          :   4/25/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY" 
        /// </summary>
        /// <param name="mtch"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetCityList(string mtch)
        {
            try
           {
               if (!Regex.IsMatch(mtch, @"[A-Za-z0-9\-]+"))
               {
                   throw new ArgumentException("Invalid format.");
               }
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " +
                              MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture,
                    " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("Calling GetCountryList method of _commonService class to get countries");
                _logMessage.Append("Calling GetCityList method of _commonService class to get city list for state");
                var cityDtoList = _commonService.GetCityList(mtch);
                _logMessage.Append("GetCityList method of _commonService executed successfully");
                _logMessage.Append("converting cityDtoList list into stateList");
                var cityViewDataList = cityDtoList.ToCityViewDataList().OrderBy(s => s.CityName).ToList();
                _logMessage.Append("convert ToCityViewDataList into cityViewDataList successful");
                _logMessage.Append("returning city list");
                List<string> list = new List<string>();
                foreach (CityViewData city in cityViewDataList)
                {
                    list.Add(city.CityName);
                }
                var cities = list.Take(10).Distinct();
                return Json(cities, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), ex);
            }
            return null;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetCarsDrivers(string id)
        {
            if (String.IsNullOrEmpty(id)) return Json(null, JsonRequestBehavior.AllowGet);
            CarDriverViewData ob = new CarDriverViewData();
            ob.CarList = _commonService.GetCars(Convert.ToInt32(id)).ToViewDataList();
            ob.DriverList = _commonService.GetDrivers(Convert.ToInt32(id)).ToViewDataList();
            return Json(ob, JsonRequestBehavior.AllowGet);
        }

    }
}

MTData.Web/Controllers/MerchantUserController.cs
using System;
using System.Web.Mvc;
using Ninject;

using MTD.Core.DataTransferObjects;
using MTD.Core.Service.Interface;
using MTData.Web.ViewData;

namespace MTData.Web.Controllers
{
    public class MerchantUserController : Controller
    {
        UserViewData _objUserViewData;
        private readonly IUserService _userService;

        public MerchantUserController([Named("UserService")] IUserService userService)
        {
            _userService = userService;
        }

        //
        // GET: /MerchantUser/
        public ActionResult Index()
        {
            int userId = Convert.ToInt32((((UserDto)Session["User"]).UserID));
            _objUserViewData = new UserViewData { UserRoles = _userService.GetUserRoles(userId).ToViewDataList() };

            return View(_objUserViewData);
        }
	}
}

MTData.Web/Controllers/SubAdminController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using Ninject;

using MTD.Core.DataTransferObjects;
using MTD.Core.Service.Interface;
using MTData.Utility;
using MTData.Web.ViewData;

namespace MTData.Web.Controllers
{
    public class SubAdminController : Controller
    {
        private StringBuilder _logMessage;
        private StringBuilder _logTracking;
        private readonly ISubAdminService _subAdminService;
        private readonly IMerchantService _merchantService;
        private readonly IUserService _userService;
        private readonly ICommonService _commonService;
        readonly ILogger _logger = new Logger();
        UserViewData _objUserViewData;

        public SubAdminController([Named("MerchantService")] IMerchantService merchantService, [Named("UserService")] IUserService userService, [Named("SubAdminService")] ISubAdminService subAdminService, [Named("CommonService")] ICommonService commonService, StringBuilder logTracking, StringBuilder logMessage)
        {
            _subAdminService = subAdminService;
            _commonService = commonService;
            _userService = userService;
            _logTracking = logTracking;
            _logMessage = logMessage;
            _merchantService = merchantService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || Session["User"] == null)
                return RedirectToAction("Index", "Member");

            int userType = ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID;
            IsFirstLoginViewData obj = new IsFirstLoginViewData();

            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Session["User"] == null || userType == 2 || userType == 3 || userType == 4)
                return RedirectToAction("Index", "Member");

            if (Session["AllInfo"] != null)
                Session.Remove("AllInfo");

            if (!(bool)Session["Islogged"])
            {
                obj.IsFirstLogin = (bool)((SessionDto)Session["User"]).SessionUser.IsFirstLogin;
                obj.UserTypeId = Convert.ToString(((SessionDto)Session["User"]).SessionUser.fk_UserTypeID);
                Session.Remove("Islogged");
                Session["Islogged"] = true;
                obj.UserId = ((SessionDto)Session["User"]).SessionUser.UserID;

                return View(obj);
            }

            obj.UserId = ((SessionDto)Session["User"]).SessionUser.UserID;
            obj.UserTypeId = Convert.ToString(((SessionDto)Session["User"]).SessionUser.fk_UserTypeID);
            return View(obj);
        }

        /// <summary>
        /// Purpose             :   To get interface for creating user
        /// Function Name       :   Create
        /// Created By          :   Asif Shafeeque 
        /// Created On          :   10/27/2014
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            int userType = 0;
            if (Session["User"] != null)
                userType = ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID;

            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || userType == 2 || userType == 3 || userType == 4) return RedirectToAction("index", "Member");

            try
            {
                int userId = ((SessionDto)Session["User"]).SessionUser.UserID;

                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("using object intilizer to GetUserRoles and convert to viewdatalist and get CountryList, StateList and CityList");

                _objUserViewData = new UserViewData
                {
                    CountryList = CountryList(),
                    MerchantList = _subAdminService.MerchantList().ToViewDataList(),
                    fk_Country = "AU"
                };

                if (userType == 5)
                {
                    _objUserViewData.MerchantList = _subAdminService.GetUserMerchant(userId).ToViewDataList();
                }

                _logMessage.Append(" CountryList, StateList and CityList list populate successfully");
                _logMessage.Append("ToViewDataList method executed successfully");
                _objUserViewData.fk_UserTypeID = userType;

                return View(_objUserViewData);
            }
            catch (Exception exception)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), exception);
            }

            return View();
        }

        /// <summary>
        /// Purpose             :   Creating Users
        /// Function Name       :   Create
        /// Created By          :   Asif Shafeeque 
        /// Created On          :   10/27/2014
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <param name="userViewdata"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(UserViewData userViewdata)
        {
            if (Session["User"] == null)
                return RedirectToAction("Index", "Member");

            int userType = ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID;
            int userId = ((SessionDto)Session["User"]).SessionUser.UserID;

            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || userType == 2 || userType == 3 || userType == 4)
                return RedirectToAction("index", "Member");

            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                
                if (!string.IsNullOrEmpty(userViewdata.fleetListId))
                    userViewdata.fleetListId = userViewdata.fleetListId.Replace("multiselect-all,", string.Empty);
                
                if (!string.IsNullOrEmpty(userViewdata.MerchantListId))
                    userViewdata.MerchantListId = userViewdata.MerchantListId.Replace("multiselect-all,", string.Empty);

                if ((String.IsNullOrEmpty(userViewdata.fleetListId)) || userViewdata.fleetListId == "multiselect-all" || userViewdata.fleetListId == "-1")
                    ModelState.AddModelError("fleetListId", "Please select a Fleet");

                if ((String.IsNullOrEmpty(userViewdata.MerchantListId)) || userViewdata.MerchantListId == "multiselect-all" || userViewdata.MerchantListId == "-1")
                    ModelState.AddModelError("MerchantListId", "Please select a Merchant");

                userViewdata.CreatedBy = ((SessionDto)Session["User"]).SessionUser.Email;
                string cPCode = Membership.GeneratePassword(10, 0);
                userViewdata.PCode = cPCode.Hash();

                userViewdata.UserRoles = _merchantService.GetUserRoles().ToViewDataList();
                userViewdata.CountryList = CountryList();
                userViewdata.MerchantList = _subAdminService.MerchantList().ToViewDataList();

                if (userType == 5)
                    userViewdata.MerchantList = _subAdminService.GetUserMerchant(userId).ToViewDataList();

                userViewdata.ParentUserID = userId;

                if (!string.IsNullOrEmpty(userViewdata.MerchantListId))
                    userViewdata.fleetlist = _subAdminService.GetFleet(userViewdata.MerchantListId, userType, userId).ToViewDataList();
                else
                    userViewdata.fleetlist = _subAdminService.GetFleet("-1", userType, userId).ToViewDataList();

                if (ModelState.IsValid)
                {
                    var res = _commonService.IsExist(userViewdata.Email);
                    if (!res)
                    {
                        userViewdata.fk_UserTypeID = userType;
                        var response = _subAdminService.Add(userViewdata.ToDTO());

                        string userName = ((SessionDto)Session["User"]).SessionUser.Email;
                        _logTracking.Append("User " + userViewdata.Email + " Sub Admin user created  by" + userName + " at " + System.DateTime.Now.ToUniversalTime());
                        _logger.LogInfoMessage(_logTracking.ToString());

                        if (response)
                        {
                            try
                            {
                                _logMessage.Append("Mail Sending begin and reading file ~/HtmlTemplate/confirmMail.html");

                                var filename = System.Web.HttpContext.Current.Server.MapPath("~/HtmlTemplate/confirmMail.html");
                                using (var myFile = new System.IO.StreamReader(filename))
                                {
                                    string msgfile = myFile.ReadToEnd();
                                    var msgBody = new StringBuilder(msgfile);
                                    myFile.Close();

                                    string cMail = userViewdata.Email;

MTData.Web/Views/Shared/CountryState.cshtml
@model MTData.Web.ViewData.MerchantUserViewData

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CountryState</title>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Country").change(function () {
                $("#State").empty();
                $("#City").empty();
                $("#hdncountry").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetStates", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#Country").val() },
                    success: function (states) {
                        $.each(states, function (i, state) {
                            $("#State").append('<option value="' + state.Value + '">' +
                                state.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
                return false;
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#State").change(function () {
                $("#City").empty();
                $("#hdnstate").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetCity", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#State").val() },
                    success: function (citys) {
                        $.each(citys, function (i, city) {
                            $("#City").append('<option value="' + city.Value + '">' + city.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
                return false;
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#City").change(function () {
                $("#hdncity").val($('option:selected', $(this)).text());
            })
        });
    </script>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            <table style="width:100%;">
                <tr>
                    <td style="width:200px">@Html.Label("Country")<span class="required">*</span></td>
                    <td>
                        @Html.Hidden("hdncountry", null, new { @id = "hdncountry" })
                        @Html.Hidden("hdnstate", null, new { @id = "hdnstate" })
                        @Html.Hidden("hdncity", null, new { @id = "hdncity" })
                        @Html.DropDownListFor(model => model.Country, ViewData["country"] as List<SelectListItem>, Model.Country, new { @class = "form-control" })
                        @Html.HiddenFor(model => model.Country)
                    </td>
                    <td class="requiredfields" style="width:200px">
                        @Html.ValidationMessageFor(model => model.Country)
                    </td>
                </tr>
                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("State")<span class="required">*</span></td>
                    <td>
                        @Html.DropDownListFor(model => model.State, new SelectList(string.Empty, "Value", "Text"), Model.State, new { @class = "form-control" })
                        @Html.HiddenFor(model => model.State)
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.State)
                    </td>
                </tr>
                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("City")<span class="required">*</span></td>
                    <td>
                        @Html.DropDownListFor(model => model.City, new SelectList(string.Empty, "Value", "Text"), Model.City, new { @class = "form-control" })
                        @Html.HiddenFor(model => model.City)
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.City)
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>

MTData.Web/Views/Shared/_ProfileCountryState.cshtml
@model MTData.Web.ViewData.MerchantUserViewData

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Country").change(function () {
                $("#State").empty();
                $("#city").empty();
                $("#hdncountry").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetStates", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#Country").val() },
                    success: function (states) {
                        $.each(states, function (i, state) {
                            $("#State").append('<option value="' + state.Value + '">' +
                                state.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
                return false;
            });
        });

    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#State").change(function () {
               
                $("#City").empty();
                $("#hdnstate").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetCity", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#State").val() },
                    success: function (citys) {
                        $.each(citys, function (i, city) {
                            $("#City").append('<option value="' + city.Value + '">' + city.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });

                return false;
            });
        });

    </script>


    <script type="text/javascript">
        $(document).ready(function () {
            $("#City").change(function () {
                $("#hdncity").val($('option:selected', $(this)).text());
            })
        });
    </script>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            <table style="width:100%;">


                <tr>
                    <td style="width:200px">@Html.Label("Country")<span class="required">*</span></td>
                    <td>
                        @Html.Hidden("hdncountry", null, new { @id = "hdncountry" })
                        @Html.Hidden("hdnstate", null, new { @id = "hdnstate" })
                        @Html.Hidden("hdncity", null, new { @id = "hdncity" })
                        @Html.DropDownListFor(model => model.Country, ViewData["country"] as List<SelectListItem>, Model.Country, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields" style="width:200px">
                        @Html.ValidationMessageFor(model => model.Country)
                    </td>
                </tr>


                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("State")<span class="required">*</span></td>
                    <td>

                        @Html.DropDownListFor(model => model.State, new SelectList(string.Empty, "Value", "Text"), Model.State, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.State)
                    </td>
                </tr>
                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("City")<span class="required">*</span></td>
                    <td>

                        @Html.DropDownListFor(model => model.City, new SelectList(string.Empty, "Value", "Text"), Model.City, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.City)
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>

MTData.Web/Views/Shared/_adminUserCountryState.cshtml
@model MTData.Web.ViewData.UserViewData

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CountryState</title>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Country").change(function () {
                $("#State").empty();
                $("#city").empty();
                $("#hdncountry").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetStates", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#Country").val() },
                    success: function (states) {
                        $.each(states, function (i, state) {
                            $("#State").append('<option value="' + state.Value + '">' +
                                state.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
                return false;
            });
        });

    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#State").change(function () {
               
                $("#City").empty();
                $("#hdnstate").val($('option:selected', $(this)).text());
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetCity", "CountryState")',
                    dataType: 'json',
                    data: { id: $("#State").val() },
                    success: function (citys) {
                        $.each(citys, function (i, city) {
                            $("#City").append('<option value="' + city.Value + '">' + city.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });

                return false;
            });
        });

    </script>


    <script type="text/javascript">
        $(document).ready(function () {
            $("#City").change(function () {
                $("#hdncity").val($('option:selected', $(this)).text());
            })
        });
    </script>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            <table style="width:100%;">


                <tr>
                    <td style="width:200px">@Html.Label("Country")<span class="required">*</span></td>
                    <td>
                        @Html.Hidden("hdncountry", null, new { @id = "hdncountry" })
                        @Html.Hidden("hdnstate", null, new { @id = "hdnstate" })
                        @Html.Hidden("hdncity", null, new { @id = "hdncity" })
                        @Html.DropDownListFor(model => model.Country, ViewData["country"] as List<SelectListItem>, Model.Country, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields" style="width:200px">
                        @Html.ValidationMessageFor(model => model.Country)
                    </td>
                </tr>


                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("State")<span class="required">*</span></td>
                    <td>

                        @Html.DropDownListFor(model => model.State, new SelectList(string.Empty, "Value", "Text"), Model.State, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.State)
                    </td>
                </tr>
                <tr><td colspan="3" class="space"></td></tr>
                <tr>
                    <td>@Html.Label("City")<span class="required">*</span></td>
                    <td>

                        @Html.DropDownListFor(model => model.City, new SelectList(string.Empty, "Value", "Text"), Model.City, new { @class = "form-control" })
                    </td>
                    <td class="requiredfields">
                        @Html.ValidationMessageFor(model => model.City)
                    </td>
                </tr>
            </table>
        }
    </div>
</body>
</html>