MTData.Web/Controllers/MerchantGatewayController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Web.Mvc;
using System.Web.Security;
using Ninject;

using MTD.Core.DataTransferObjects;
using MTD.Core.Service.Interface;
using MTData.Web.ViewData;
using MTData.Utility;
using MTData.Web.Resource;

namespace MTData.Web.Controllers
{
    public class MerchantGatewayController : Controller
    {
        readonly ILogger _logger = new Logger();
        private readonly IMerchantGatewayService _merchantGatewayService;
        private readonly ICommonService _commonService;
        private StringBuilder _logMessage;
        private StringBuilder _logTracking;

        public MerchantGatewayController([Named("MerchantGatewayService")] IMerchantGatewayService gatewayService, [Named("CommonService")] ICommonService commomService, StringBuilder logMessage, StringBuilder logTracking)
        {
            _merchantGatewayService = gatewayService;
            _commonService = commomService;
            _logMessage = logMessage;
            _logTracking = logTracking;
        }

        /// <summary>
        /// Purpose             :   to display Merchant gateway
        /// Function Name       :   Index
        /// Created By          :   Naveen Kumar 
        /// Created On          :   1/19/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID != 1)
                return RedirectToAction("index", "Member");

            return View();
        }

        /// <summary>
        /// Purpose             :   Creating Merchant gateway
        /// Function Name       :   Create
        /// Created By          :    Naveen Kumar 
        /// Created On          :   1/19/2015
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID != 1)
                return RedirectToAction("index", "Member");

            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("using object initilizar for MerchantGatewayViewData and getting list of Gateway and TypeList");

                var gatewayView = new MerchantGatewayViewData
                {
                    GatewayList = GatewayList(),
                    TypeList = TypeList(),
                    GatewayType = 2
                };

                _logMessage.Append("list of Gateway and TypeList successfully bind");

                return View(gatewayView);
            }
            catch (Exception exception)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), exception);
            }

            return View();
        }

        /// <summary>
        /// Purpose             :   Creating Merchant gateway
        /// Function Name       :   Create
        /// Created By          :     Naveen Kumar  
        /// Created On          :   1/20/2015
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <param name="gatewayViewData"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(MerchantGatewayViewData gatewayViewData)
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null) return RedirectToAction("index", "Member");

            try
            {
                var httpCookie = Request.Cookies["CookieViewAs"];
                if (httpCookie != null)
                    gatewayViewData.fk_MerchantID = Convert.ToInt32(httpCookie["merchantId"]);

                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("getting list of Gateway and TypeList");

                gatewayViewData.GatewayList = GatewayList();
                gatewayViewData.TypeList = TypeList();

                _logMessage.Append("list of Gateway and TypeList successfully bind");

                if (ModelState.IsValid)
                {
                    gatewayViewData.IsMtdataGateway = FindGatewayType(gatewayViewData);

                    _logMessage.Append("calling ToMerchantGatewayDto method to map MerchantGatewayDto to MerchantGatewayViewData and retrun MerchantGatewayDto");

                    var gatewayDto = gatewayViewData.ToMerchantGatewayDto();
                    _logMessage.Append("ToMerchantGatewayDto method executed successfully");

                    gatewayDto.CreatedBy = (((SessionDto)Session["User"]).SessionUser.Email);

                    _logMessage.Append("Calling Add method of _merchantGatewayService class takes gatewayDto, gatewayDto properties Company = " + gatewayViewData.Company + ", Created By = " + gatewayViewData.CreatedBy + ", Gateway Type = " + gatewayViewData.GatewayType + ", IsActive= " + gatewayViewData.IsActive + ", Is Mtdata Gateway= " + gatewayViewData.IsMtdataGateway + ", Name= " + gatewayViewData.Name + ", UserName = " + gatewayViewData.UserName + ", Password= " + gatewayViewData.PCode);

                    bool isExist = _merchantGatewayService.Add(gatewayDto);
                    if (isExist)
                    {
                        _logMessage.Append("Default gateway has been already set returning to view");
                        ViewBag.Message = MtdataResource.default_gateway;
                        return View(gatewayViewData);
                    }

                    string userName = ((SessionDto)Session["User"]).SessionUser.Email;
                    _logTracking.Append("User " + userName + " add  merchant gateway" + gatewayDto.Name+ " at " + System.DateTime.Now.ToUniversalTime());
                    _logger.LogInfoMessage(_logTracking.ToString());
                    _logMessage.Append("Add method of _merchantGatewayService class executed successfully");

                    return RedirectToAction("Index");
                }

                return View(gatewayViewData);
            }
            catch (Exception ex)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), ex);
            }

            return View();
        }

        /// <summary>
        /// Purpose             :   updating Merchant gateway
        /// Function Name       :  update
        /// Created By          :   Naveen Kumar 
        /// Created On          :   1/20/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <param name="merchantGatewayId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Update(int merchantGatewayId)
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID != 1)
                return RedirectToAction("index", "Member");

            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("Calling GetMerchantGatewayDto method of _merchantGatewayService class takes merchantGatewayId = " + merchantGatewayId);

                var gatewayDto = _merchantGatewayService.GetMerchantGatewayDto(merchantGatewayId);

                _logMessage.Append("GetMerchantGatewayDto method of _merchantGatewayService executed successfully");
                _logMessage.Append("calling ToMerchantGatewayViewData method to map MerchantGatewayViewData to MerchantGatewayDto and retrun MerchantGatewayViewData");

                MerchantGatewayViewData gatewayViewData = gatewayDto.ToMerchantGatewayViewData();

                _logMessage.Append("ToMerchantGatewayViewData method executed successfully");
                _logMessage.Append("getting list of Gateway and TypeList");

                gatewayViewData.GatewayList = GatewayList();
                gatewayViewData.TypeList = TypeList();

                _logMessage.Append("list of Gateway and TypeList successfully bind returing to view");

                return View(gatewayViewData);
            }
            catch (Exception exception)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), exception);
            }

            return View();
        }

        /// <summary>

MTData.Web/Views/MerchantGateway/Create.cshtml
@using MTD.Core.DataTransferObjects
@model MTData.Web.ViewData.MerchantGatewayViewData
@{
    ViewBag.Title = "Add Merchant Gateway";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>  Merchant Gateway    </title>
    <script src="~/Scripts/txt-validation.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <style type="text/css">
        .Validate {
            color: red;
            padding-left: 6px;
            position: absolute;
        }
        td {
            padding-top: .3em;
            padding-bottom: .3em;
        }

        th {
            background-color: #014a81;
        }
        .required {
            color: red;
        }
    </style>
</head>

<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
            {
                var user = ((SessionDto)Session["User"]).SessionUser.FName;
            <h3> Welcome   @user</h3>
            }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>
            @{
                Html.RenderAction("_SettingMerchant", "Member");
            }
        </div>
        <div class="right-panel">
            <div class="right-content">
                <div class="content-sec">
                    @using (Html.BeginForm())
                {
                @Html.AntiForgeryToken()
                <div class="">
                    <h4>Add Gateway</h4>
                    <hr />
                    @Html.ValidationSummary(true)
                    <table style="width:65%">
                        <tr>
                          
                            <td colspan="2">
                                @if (ViewBag.Message != null)
                                    {
                                    <p style="color: green; font-size: 16px">&nbsp;@ViewBag.Message</p>
                                    }

                            </td>
                        </tr>
                        <tr>
                            <td>@Html.Label("Gateway")<span class="required">*</span></td>
                            <td>
                                @Html.DropDownListFor(m => m.fk_GatewayID, new SelectList(Model.GatewayList, "GatewayID", "Name", Model.fk_GatewayID),"--Select Gateway--", new { @class = "form-control",@id = "ddlGateway" })
                            </td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.fk_GatewayID) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("UserName", new { @id = "lblUserName" })@Html.Label("", new { style = "color: red" })</td>
                            <td>@Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @id = "txtUserName", onkeyup = "AllowCharsSpace(this, 30)" })</td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.UserName) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("Password", new { @id="lblPassword"})@Html.Label("", new { style = "color: red" })</td>
                            <td>@Html.PasswordFor(model => model.Password, new { @class = "form-control", @id = "txtPassword", onkeyup = "LengthOnly(this, 30)" })</td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.Password) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("Is Default")</td>
                            <td>@Html.CheckBoxFor(model=>model.IsDefault)
                            
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>
                                <input type="submit" class="btnu" value="Create" />&nbsp;&nbsp;&nbsp;<a href="~/MerchantGateway" class="btn1">Cancel</a>
                            </td>
                        </tr>
                    </table>

                </div>
                }
                </div>

            </div>
        </div>

    </div>
    <script type="text/javascript">
        $(document).ready(function()
        {
            $("#txtUserName").val("");
            $("#txtPassword").val("");
        })
        $("#ddlGateway").change(function()
        {
            $("#txtUserName").val("");
            $("#txtPassword").val("");
        })
   
    </script>

</body>
<script type="text/javascript">
    function active() {
        document.getElementById("vas").className += " activeLi" + " activemenu";
    }
</script>

MTData.Web/Views/MerchantGateway/Index.cshtml
@using MTD.Core.DataTransferObjects
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;
}

<head>
    <title>  Merchant Gateway    </title>
</head>
<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
                {
                    var user = ((SessionDto)Session["User"]).SessionUser.FName;
                    <h3> Welcome   @user</h3>
                }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>
            @{

                Html.RenderAction("_SettingMerchant", "Member");
            }
        </div>


        <div class="right-panel">
            <div class="right-content">

                <div class="content-sec">
                    <table style="width:100%">
                        <tr>
                            <td><h4> @Html.ActionLink("Add Merchant Gateway", "Create", "MerchantGateway")</h4></td>
                            <td style="float:right">

                                <form>
                                    <div class="search-box">
                                        <input type="text" value="" name="Name" id="Name" placeholder="Search : Gateway name">
                                        <span class="search-icon">
                                            <input type="submit" value="" id="LoadRecordsButton" class="search-btn" />
                                        </span>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    </table>

                    <div id="StudentTableContainer"></div>
                    <script type="text/javascript">

                        $(document).ready(function () {

                            $('#StudentTableContainer').jtable({
                                // title: 'Payment Gateway',
                                paging: true,
                                pageSize: 15,
                                sorting: true,
                                defaultSorting: 'Name ASC',
                                actions: {
                                    listAction: '/MerchantGateway/MerchantGateListByFilter',
                                    deleteAction: '/MerchantGateway/Delete',
                                },
                                fields: {
                                    MerchantGatewayID: {
                                        key: true,
                                        create: false,
                                        edit: false,
                                        list: false
                                    },
                                    
                                    Name: {
                                        title: 'Gateway Name',
                                        width: '35%'

                                    },
                                    IsDefault: {
                                        title: 'Is Default',
                                        sorting: false,
                                        width: '15%',
                                        type: 'checkbox',
                                        values: { 'false': 'No', 'true': 'Yes' },
                                    },
                                    UserName: {
                                        title:'User Name',
                                        width: '25%',
                                        sorting: false
                                    },
                                    Edit: {
                                        title: 'Actions',
                                        sorting: false,
                                        width: '10%',
                                        display: function (data) {
                                            return '<a  href="MerchantGateway/Update?merchantGatewayId=' + data.record.MerchantGatewayID + '"><img src="../Scripts/jtable/themes/metro/edit.png" title="Edit"/></a>';

                                        }
                                    },
                                }
                            });

                            //Re-load records when user click 'load records' button.
                            $('#LoadRecordsButton').click(function (e) {
                                e.preventDefault();
                                $('#StudentTableContainer').jtable('load', {
                                    name: $('#Name').val(),
                                });
                            });

                            //Load all records when page is first shown
                            $('#LoadRecordsButton').click();
                        });

                    </script>
                </div>

            </div>
        </div>

    </div>
</body>


<script type="text/javascript">
    function active() {
        document.getElementById("vas").className += " activeLi" + " activemenu";
    }
</script>

MTData.Web/Views/MerchantGateway/Update.cshtml
@using MTD.Core.DataTransferObjects
@model MTData.Web.ViewData.MerchantGatewayViewData
@{
    ViewBag.Title = "Update Merchant Gateway";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>  Merchant Gateway    </title>
    <script src="~/Scripts/txt-validation.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <style type="text/css">
        .Validate {
            color: red;
            padding-left: 6px;
            position: absolute;
        }

        td {
            padding-top: .3em;
            padding-bottom: .3em;
        }

        th {
            background-color: #014a81;
        }

        .required {
            color: red;
        }
    </style>
</head>
<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
            {
                var user = ((SessionDto)Session["User"]).SessionUser.FName;
            <h3> Welcome   @user</h3>
            }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>
            @{
                Html.RenderAction("_SettingMerchant", "Member");
            }
        </div>
        <div class="right-panel">
            <div class="right-content">
                <div class="content-sec">
                    @using (Html.BeginForm())
                {
                @Html.AntiForgeryToken()
                <div class="">
                    <h4>Update Gateway</h4>
                    <hr />
                    @Html.ValidationSummary(true)
                    <table style="width:50%">
                        <tr>
                            <td style="width:200px">&nbsp;</td>
                            <td style="width:355px">
                                @if (ViewBag.Message != null)
                                    {
                                    <p style="color: green;font-size:16px">&nbsp;@ViewBag.Message</p>
                                    }

                            </td>
                        </tr>
                  
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("Gateway")<span class="required">*</span></td>
                            <td>
                                @Html.DropDownListFor(m => m.fk_GatewayID, new SelectList(Model.GatewayList, "GatewayID", "Name", Model.fk_GatewayID), "--Select Gateway--", new { @class = "form-control", @id = "ddlGateway" })
                            </td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.fk_GatewayID) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("UserName", new {@id="lblUserName" })@Html.Label("", new { style = "color: red" })</td>
                            <td>@Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @id = "txtUserName", onkeyup = "AllowCharsSpace(this, 30)" })</td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.UserName) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("Password", new { @id="lblPassword"})@Html.Label("", new { style = "color: red" })</td>
                            <td>@Html.PasswordFor(model => model.Password, new { @class = "form-control", @id = "txtPassword", onkeyup = "LengthOnly(this, 30)" })</td>
                            <td class="Validate"> @Html.ValidationMessageFor(model => model.Password) </td>
                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>@Html.Label("Is Default")</td>
                            <td>@Html.CheckBoxFor(model => model.IsDefault)

                        </tr>
                        <tr><td class="space"></td></tr>
                        <tr><td class="space"></td></tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>
                                <input type="submit" class="btnu" value="Update" />&nbsp;&nbsp;&nbsp;<a href="~/MerchantGateway" class="btn1">Cancel</a>
                            </td>
                        </tr>
                    </table>

                </div>
                }
                </div>

            </div>
        </div>

    </div>
    

</body>
<script type="text/javascript">
    function active() {
        document.getElementById("mgg").className += "activeLi";
    }
</script>