MTData.Web/Controllers/MemberController.cs
using System;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Configuration;
using System.Configuration;
using Ninject;

using MTD.Core.Service.Interface;
using MTD.Core.DataTransferObjects;
using MTData.Utility;
using MTData.Web.Resource;
using MTData.Web.ViewData;

namespace MTData.Web.Controllers
{
    public class MemberController : Controller
    {
        private readonly IUserService _userService;
        readonly ILogger _logger = new Logger();
        private readonly IMemberService _loginService;
        private StringBuilder _logMessage;
        private StringBuilder _logTracking;

        public MemberController([Named("LoginService")] IMemberService loginService, [Named("UserService")] IUserService userService, StringBuilder logMessage, StringBuilder logTracking)// need to register
        {
            _loginService = loginService;
            _userService = userService;
            _logMessage = logMessage;
            _logTracking = logTracking;
        }

        /// <summary>
        /// Purpose             :   To login the user
        /// Function Name       :   Index
        /// Created By          :   Umesh Kumar
        /// Created On          :   16/12/2014
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>         
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            bool doEncrypt = Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["isEncrypt"]);
            if (doEncrypt)
                Encrypt();
            return View();
        }

        /// <summary>
        /// Purpose             :   To provide the password when user have forgotted password and do log in
        /// Function Name       :   ForgotPassword
        /// Created By          :   Umesh Kumar
        /// Created On          :   17/12/2014
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>         
        /// <returns></returns>
        [HttpGet]
        public ActionResult ForgotPassword()
        {
            return View("ForgotPassword");
        }

        /// <summary>
        /// Purpose             :   To provide the password when user have forgotted password and do log in
        /// Function Name       :   ForgotPassword
        /// Created By          :   Umesh Kumar
        /// Created On          :   17/12/2014
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary> 
        /// <param name="loginView"></param>        
        /// <returns></returns>
        [HttpPost]
        public ActionResult ForgotPassword(LoginViewData loginView)
        {
            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));

                if (loginView.UserName == null)
                {
                    ModelState.AddModelError("UserName", MtdataResource.Please_Enter_Email);
                    return View();
                }

                _logMessage.Append("calling GetPassword method of _loginService takes parameter username as email= " + loginView.UserName + " to get password");

                var userDto = _loginService.GetPassword(loginView.UserName);

                _logMessage.Append("calling GetPassword method of _loginService executed successfully");

                if (userDto == null)
                {
                    TempData["PasswordSent"] = MtdataResource.invalid_Email_Forgot_Password; //"Invalid account, please enter valid email adderss.";
                    return View();
                }

                _logMessage.Append("calling CreateRandomString method of StringExtension class to genrate a random Password");

                string resetPCode = StringExtension.CreateRandomString(10);

                _logMessage.Append("CreateRandomString method of StringExtension class to genrate a random Password= " + resetPCode);
                _logMessage.Append("calling Hash method of StringExtension class to encrypt Password");

                string encryptPCode = StringExtension.Hash(resetPCode);

                _logMessage.Append("Hash method of StringExtension class to genrate a Hash Password= " + encryptPCode);
                _logMessage.Append("getting html file ~/HtmlTemplate/password.html from server");

                string filename = System.Web.HttpContext.Current.Server.MapPath("~/HtmlTemplate/password.html");

                try
                {
                    _logMessage.Append("Mail Sending begin and reading file ~/HtmlTemplate/password.html");

                    using (var myFile = new StreamReader(filename))
                    {
                        string msgfile = myFile.ReadToEnd();
                        var msgBody = new StringBuilder(msgfile);
                        msgBody.Replace("[##UserName##]", userDto.FName);
                        msgBody.Replace("[##email##]", loginView.UserName);
                        msgBody.Replace("[##password##]", resetPCode);

                        var utility = new EmailUtil();

                        _logMessage.Append("calling SendMail method of utility class to send a mail with various parameters " + loginView.UserName + ", " + msgBody + ", MTData , MTData member password");
                        _logMessage.Append("calling Reset method of _loginService class takes email and encrypt password= " + userDto.Email + ", " + encryptPCode);

                        bool updateUser = _loginService.Reset(userDto.Email, encryptPCode);

                        _logMessage.Append("calling Reset method of _loginService executed successfully");

                        if (updateUser)
                        {
                            _logMessage.Append("password Reset successfully");

                            TempData["PasswordSent"] = MtdataResource.invalid_Email_Forgot_Password; //  "Your passwrod has been reset successfully, please check your email.";

                            _logMessage.Append("calling SendMail method of utility class");

                            utility.SendMail(loginView.UserName, msgBody.ToString(), "MTI Admin", "MTI member password");
                        }
                        else
                            TempData["PasswordSent"] = MtdataResource.invalid_Email_Forgot_Password;

                        _logMessage.Append("returning to view");
                        return View();
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogInfoFatal(_logMessage.ToString(), ex);
                }
            }
            catch (Exception exception)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), exception);
                HttpContext.AddError(new HttpException(949, MtdataResource.Invalid_ID)); //"Invalid Id"));
            }

            return View();
        }

        /// <summary>
        /// Purpose             :   To login the user
        /// Function Name       :   Index
        /// Created By          :   Umesh Kumar
        /// Created On          :   18/12/2014
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary> 
        /// <param name="loginView"></param>        
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(LoginViewData loginView)
        {
            if (!string.IsNullOrEmpty(loginView.UserName) && !string.IsNullOrEmpty(loginView.PCode))
            {
                try
                {
                    Session.Remove("Islogged");
                    Session.Remove("User");
                    Session.Remove("isAdmin");

                    _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                    _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));

                    _logMessage.Append("calling Hash method to encrypt the password");
                    _logMessage.Append("Hash method to encrypt the password executed successfully");

                    LoginDto loginDto = ViewDataExtention.CreateLoginDto(loginView);

                    _logMessage.Append("calling Login method of _loginService takes loginDto parameters are: username as email= " + loginView.UserName + " and password= " + loginView.PCode);

                    bool isLocked = _loginService.IsLocked(loginDto.UserName);

                    if (isLocked)
                    {
                        ViewBag.Message = MtdataResource.User_Locked;
                        return View();
                    }

                    SessionDto user = _loginService.Login(loginDto);
                    if (user != null)
                    {
                        Session["User"] = user;
                        Session["Islogged"] = false;
                        FormsAuthentication.SetAuthCookie(user.SessionUser.Email, false);

                        _logMessage.Append("session user is not null");

                        Session["isAdmin"] = "Admin";

                        if (((SessionDto)Session["User"]).SessionUser.fk_UserTypeID == 0)
                        {

MTData.Web/Views/SummaryReport/Display.cshtml
@using MTD.Core.DataTransferObjects
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<head>
    <title>
        Summary Report Reciepient
    </title>
</head>
<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
                {
                    var user = ((SessionDto)Session["User"]).SessionUser.FName;
                    <h3> Welcome   @user</h3>
                }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>

            @{
                Html.RenderAction("_MerchantUsers", "Member");
            }
        </div>
        <div class="right-panel">
            <div class="right-content">
                <div class="content-sec">
                    <table style="width:100%">
                        <tr>
                            <td><h5>Weekly Trans Count Report</h5>
                            </td>
                            <td style="float:right">
                                <form>
                                    <div class="search-box">
                                        <input type="text" name="Search" id="name" placeholder="Search : Report">
                                        <span class="search-icon">
                                            <input type="submit" value="" id="LoadRecordsButton" class="search-btn" />
                                        </span>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    </table>
                    <div id="StudentTableContainer"></div>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#StudentTableContainer').jtable({
                                paging: true,
                                pageSize: 15,
                                headerHeight: 40,
                                sorting: true,
                                defaultSorting: 'FleetName ASC',
                                actions: {
                                    listAction: '/SummaryReport/WeeklyCountReportListByFiter',
                                   // deleteAction: '/ScheduleReport/Delete',
                                    setAutoResizeMode: true
                                },
                                fields: {
                                    ScheduleID: {
                                        key: true,
                                        create: false,
                                        edit: false,
                                        list: false
                                    },
                                    FleetName: {
                                        title: 'Fleet Name',
                                        width: '13%',
                                        sorting: true
                                    },
                                    TransCountThisWeek: {
                                        title: 'ThisWeeksTxn',
                                        
                                        width: '13%',
                                        sorting: true
                                    },
                                    TransCountWeekFirst: {
                                        title: 'OneWeeksAgoTxn',
                                       
                                        width: '13%',
                                         
                                        sorting: true
                                    },
                                    TransCountWeekSecond: {
                                        title: 'TwoWeeksAgoTxn',
                                        width: '14%',
                                        sorting: true
                                    },
                            
                                    TransCountWeekThird: {
                                        title: 'ThreeWeeksAgoTxnCount',
                                        width: '16%',
                                        sorting: true
                                    },
                                    TransCountWeekFourth: {
                                        title: 'FourWeeksAgoTxn',
                                        width: '13%',
                                        sorting: false
                                    },
                                    TransCountWeekFifth: {
                                        title: 'FiveWeeksAgoTxn',
                                        width: '13%',
                                        sorting: false
                                    },
                                    TransCountWeekSixth: {
                                        title: 'SixWeeksAgoTxn',
                                        sorting: false
                                    } ,
                                   
                                }
                            });
                            $('#LoadRecordsButton').click(function (e) {
                                e.preventDefault();
                                $('#StudentTableContainer').jtable('load', {
                                    name: $('#name').val(),
                                });
                            });
                            $('#LoadRecordsButton').click();
                        });

                    </script>
                </div>

            </div>
        </div>

    </div>
</body>
<script type="text/javascript">
    //function active() {
    //    document.getElementById("schrep").className += " activeLi" + " activemenu";
    //    var mydate = new Date();
    //    mydate.setTime(mydate.getTime() - 1);
    //    document.cookie = "CookieViewAs=; expires=" + mydate.toGMTString();
    //}

    $(document).ready(function () {
       
        document.getElementById("wkRpt").className += " activeLi" + " activemenu";
        $("#wkRptColl").css("display", "block");
      
    });
</script>

MTData.Web/Views/SummaryReport/DollarVolumeDisplay.cshtml
@using MTD.Core.DataTransferObjects
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<head>
    <title>
        Weekly Dollar Volume Report
    </title>
</head>
<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
                {
                    var user = ((SessionDto)Session["User"]).SessionUser.FName;
                    <h3> Welcome   @user</h3>
                }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>

            @{
                Html.RenderAction("_MerchantUsers", "Member");
            }
        </div>
        <div class="right-panel">
            <div class="right-content">
                <div class="content-sec">
                    <table style="width:100%">
                        <tr>
                            <td><h6><b>Weekly Dollar Volume Report</b></h6></td>
                            <td style="float:right">
                                <form>
                                    <div class="search-box">
                                        <input type="text" name="Search" id="name" placeholder="Search : Report">
                                        <span class="search-icon">
                                            <input type="submit" value="" id="LoadRecordsButton" class="search-btn" />
                                        </span>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    </table>
                    <div id="StudentTableContainer"></div>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            $('#StudentTableContainer').jtable({
                                paging: true,
                                pageSize: 15,
                                headerHeight: 40,
                                sorting: true,
                                defaultSorting: 'FleetName ASC',
                                actions: {
                                    listAction: '/SummaryReport/WeeklyDollarVolumeReportListByFiter',
                                    setAutoResizeMode: true
                                },
                                fields: {
                                    ScheduleID: {
                                        key: true,
                                        create: false,
                                        edit: false,
                                        list: false
                                    },
                                    FleetName: {
                                        title: 'Fleet Name',
                                        width: '13%',
                                        sorting: true
                                    },
                                    TransAmtThisWeek: {
                                        title: 'ThisWeekTxnAmt',

                                        width: '13%',
                                        sorting: true
                                    },
                                    TransAmtWeekOne: {
                                        title: 'OneWeekAgoTxnAmt',

                                        width: '13%',

                                        sorting: true
                                    },
                                    TransAmtWeekTwo: {
                                        title: 'TwoWeeksAgoTxnAmt',
                                        width: '14%',
                                        sorting: true
                                    },

                                    TransAmtWeekThree: {
                                        title: 'ThreeWeeksAgoTxnAmt',
                                        width: '16%',
                                        sorting: true
                                    },
                                    TransAmtWeekFour: {
                                        title: 'FourWeeksAgoTxnAmt',
                                        width: '13%',
                                        sorting: true
                                    },
                                    TransAmtWeekFive: {
                                        title: 'FiveWeeksAgoTxnAmt',
                                        width: '13%',
                                        sorting: true
                                    },
                                    TransAmtWeekSix: {
                                        title: 'SixWeeksAgoTxnAmt',
                                        sorting: true
                                    },

                                }
                            });
                            $('#LoadRecordsButton').click(function (e) {
                                e.preventDefault();
                                $('#StudentTableContainer').jtable('load', {
                                    name: $('#name').val(),
                                });
                            });
                            $('#LoadRecordsButton').click();
                        });

                    </script>
                </div>

            </div>
        </div>

    </div>
</body>
<script type="text/javascript">
    //function active() {
    //    document.getElementById("schrep").className += " activeLi" + " activemenu";
    //    var mydate = new Date();
    //    mydate.setTime(mydate.getTime() - 1);
    //    document.cookie = "CookieViewAs=; expires=" + mydate.toGMTString();
    //}

    $(document).ready(function () {

        document.getElementById("wkRpt").className += " activeLi" + " activemenu";
        $("#wkRptColl").css("display", "block");

    });
</script>