MTData.Web/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Web.Mvc;
using System.Web.Security;
using System.Web;
using System.IO;
using System.Data;
using System.Text.RegularExpressions;
using Ninject;

using MTD.Core.DataTransferObjects;
using MTD.Core.Service.Interface;
using MTData.Utility;
using MTData.Web.ViewData;
using MTData.Web.Resource;

namespace MTData.Web.Controllers
{
    public class VehicleController : Controller
    {
        readonly ILogger _logger = new Logger();
        private readonly IVehicleService _vehicleService;
        private readonly ICommonService _commonService;
        private readonly ITerminalService _terminalService;
        private readonly IUserService _userService;
        private readonly IFleetService _fleetService;
        private StringBuilder _logMessage;
        private StringBuilder _logTracking;

        public VehicleController([Named("UserService")] IUserService userService, [Named("VehicleService")] IVehicleService vehicleService, [Named("CommonService")] ICommonService commomService, [Named("TerminalService")] ITerminalService terminalService, [Named("FleetService")] IFleetService fleetService, StringBuilder logMessage, StringBuilder logTracking)
        {
            _vehicleService = vehicleService;
            _commonService = commomService;
            _terminalService = terminalService;
            _logMessage = logMessage;
            _userService = userService;
            _logTracking = logTracking;
            _fleetService = fleetService;
        }

        /// <summary>
        ///  Purpose            :   to display the vehicle
        /// Function Name       :   Index
        /// Created By          :   Naveen Kumar
        /// Created On          :   1/6/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY" 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID == 1)
                return RedirectToAction("index", "Member");

            return View();
        }

        /// <summary>
        /// Purpose             :   To export list in excel file
        /// Function Name       :   Index
        /// Created By          :   Umesh Kumar
        /// Created On          :   01/28/2016
        /// Modification Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY"
        /// </summary>
        /// <param name="carOwner"></param>
        /// <param name="vehicleNumber"></param>
        /// <param name="androidMac"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(string carOwner, string vehicleNumber, string androidMac)
        {
            try
            {
                _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
                _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
                _logMessage.Append("Calling GetAdminUserListByFilter method of adminUserService class to get Admin Users List");
                
                int viewDataListCount = 0;
                IEnumerable<VehicleDto> userVechile = new List<VehicleDto>();

                var sessionData = (SessionDto)Session["User"];
                int merchantId = Convert.ToInt32(sessionData.SessionUser.fk_MerchantID);
                int logOnByUserId = Convert.ToInt32(sessionData.SessionUser.LogOnByUserId);
                int logOnByUserType = Convert.ToInt32(sessionData.SessionUser.LogOnByUserType);
                int userType = sessionData.SessionUser.fk_UserTypeID;

                FilterSearchParametersDto searchDto = new FilterSearchParametersDto()
                {
                    Name = vehicleNumber,
                    StartIndex = 0,
                    PageSize = 0,
                    Sorting = string.Empty,
                    MerchantId = merchantId,
                    LogOnByUserId = logOnByUserId,
                    LogOnByUserType = logOnByUserType,
                    OwnerName = carOwner,
                    SerialNumber = androidMac
                };

                if (userType != 4)
                {
                    userVechile = _vehicleService.GetVehileListByFilter(searchDto);
                    viewDataListCount = _vehicleService.GetVehileCount(searchDto).Count();
                }

                int userId = sessionData.SessionUser.UserID;
                var userfleet = _userService.GetUsersFleet(userId);//2

                if (userType == 4)
                {
                    FilterSearchParametersDto filterSearch = new FilterSearchParametersDto()
                    {
                        Name = vehicleNumber,
                        StartIndex = 0,
                        PageSize = 0,
                        Sorting = string.Empty,
                        MerchantId = merchantId,
                        UserId = userId,
                        UserType = userType,
                        userFleet = userfleet,
                        OwnerName = carOwner,
                        LogOnByUserType = logOnByUserType,
                        LogOnByUserId = logOnByUserId,
                        SerialNumber = androidMac
                    };

                    viewDataListCount = _vehicleService.UserVehicleCount(filterSearch);
                    filterSearch.PageSize = viewDataListCount;
                    userVechile = _vehicleService.UserVehicleList(filterSearch);
                }

                if (viewDataListCount > 1)
                {
                    using (StringWriter output = new StringWriter())
                    {
                        output.WriteLine("\"Car Owner\",\"Vehicle Number\",\"Vehicle Reg No\",\"Plate Number\",\"Fleet Name\",\"Mac Add\"");

                        foreach (VehicleDto item in userVechile)
                        {
                            output.WriteLine("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\"",
                               item.CarOwnerName, item.VehicleNumber, item.VehicleRegNo, item.PlateNumber, item.FleetName, item.DeviceName);
                        }

                        _logTracking.Append("Transaction Report Excel file Downloaded by " + (((SessionDto)Session["User"]).SessionUser.Email) + "at " + System.DateTime.Now.ToUniversalTime());
                        _logger.LogInfoMessage(_logTracking.ToString());

                        return File(new UTF8Encoding().GetBytes(output.ToString()), "application/CSV", "Vehicles.csv");
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogInfoFatal(_logMessage.ToString(), ex);
            }

            return View();
        }

        /// <summary>
        ///  Purpose            :  Fetching the Vehicle on the basis of its ID from the database.
        /// Function Name       :   Create
        /// Created By          :   Naveen Kumar
        /// Created On          :   1/6/2015
        /// Modifications Made   :   ****************************
        /// Modified On       :   ##/##/#### "MM/DD/YYYY" 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["User"] == null) return RedirectToAction("Index", "Member");
            if (Request.Cookies[FormsAuthentication.FormsCookieName] == null || ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID == 1)
                return RedirectToAction("index", "Member");

            _logMessage.Append("Controller Name:-" + GetType().Name + "; Method Name :- " + MethodBase.GetCurrentMethod().Name + ";");
            _logMessage.Append(String.Format(CultureInfo.InvariantCulture, " Date:-" + DateTime.Now.ToShortDateString() + "; Time:- " + DateTime.Now.ToShortTimeString()));
            _logMessage.Append("using object intilizer to populate fleetlist and terminal list");

            int userId = ((SessionDto)Session["User"]).SessionUser.UserID;
            int userType = ((SessionDto)Session["User"]).SessionUser.fk_UserTypeID;
            int merchantId = Convert.ToInt32(((SessionDto)Session["User"]).SessionUser.fk_MerchantID);
            int logOnByUserId = Convert.ToInt32((((SessionDto)Session["User"]).SessionUser.LogOnByUserId));
            int logOnByUserType = Convert.ToInt32((((SessionDto)Session["User"]).SessionUser.LogOnByUserType));

            try
            {
                var vehicleView = new VehicleViewData();
                vehicleView.TerminalList = TerminalList();

                if (userType == 2 || userType == 3)
                {
                    vehicleView.FleetList = FleetList(merchantId);

                    if (logOnByUserType == 5)
                    {
                        List<int> fleetListAccessed = _fleetService.GetAccesibleFleet(logOnByUserId, merchantId);                       
                        List<FleetListViewData> fleetViewResult = vehicleView.FleetList.Where(m => fleetListAccessed.Contains((int)m.FleetID)).Select(m => m).Distinct().ToList();                       
                        vehicleView.FleetList = fleetViewResult.AsEnumerable();
                    }

                    vehicleView.CarOwnerList = _vehicleService.CarOwnerList(merchantId).ToCarOwnerList();
                }

                if (userType == 4)
                {

MTData.Web/Views/Vehicle/Create.cshtml
@using MTD.Core.DataTransferObjects
@model MTData.Web.ViewData.VehicleViewData
@{
    ViewBag.Title = "Add Vehicle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>Add New Vehicle
</title>
    <script src="~/Scripts/txt-validation.js"></script>
    <script src="~/Scripts/txt-validation.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/js/bootstrap-filestyle.js"></script>

    <script src="~/js/alertbox/jquery.js"></script>
    <script src="~/js/alertbox/jquery.ui.draggable.js"></script>
    <script src="~/js/alertbox/jquery.alerts.js"></script>
    <link href="~/js/alertbox/jquery.alerts.css" rel="stylesheet" />
    <script src="~/Scripts/Loader.js"></script>
    <link href="~/css/Loader.css" rel="stylesheet" />
<style type="text/css">
    .Validate {
        color: red;
        padding-left: 6px;
        position: absolute;
            left: 526px;
    }

    td {
        padding-top: .3em;
        padding-bottom: .3em;
    }

    th {
        background-color: #014a81;
    }

    .required {
        color: red;
    }
    .browse-btn-dt {
        width: 280px;
    }

        .browse-btn-dt .bootstrap-filestyle .form-control {
            background-color: #fff;
        }

    .group-span-filestyle.input-group-btn label {
        margin-top: 0;
        font-family: Arial;
        font-size: 13px;
        padding: 7px 7px;
        font-weight: normal !important;
    }
</style>
</head>

<body onload="active()">
<div class="container-main">
    <div class="left-panel">
        <div class="user">
            @if (Session["User"] != null)
            {
                   var user = ((SessionDto)Session["User"]).SessionUser.FName;
                <h3> Welcome   @user</h3>
            }
            <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
        </div>
        @{
            Html.RenderAction("_MerchantUsers", "Member");
        }
    </div>
    <div class="right-panel">
        <div class="right-content">
            <div class="content-sec">
                 @using (Html.BeginForm("Create", "Vehicle", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Form1" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="">
                        <h4>Add Car</h4>
                        <hr />
                        @Html.ValidationSummary(true)
                            <table >
                            <tr>
                                <td style="width:200px">&nbsp;</td>
                                <td style="width:455px">
                                    @if (ViewBag.Message != null)
                                    {
                                        <p style="color: red;font-size:14px">&nbsp;@ViewBag.Message</p>
                                    }

                                </td>
                            </tr>
                                <tr><td class="space"></td></tr>
                                <tr>
                                    <td style="width:200px">@Html.Label("Input Type")</td>
                                    <td class="input-box">
                                        @Html.RadioButton("Manual", "Manual", true, new { @Name = "radiobutton", @checked = "checked", @value = "Manual", @text = "Excel", @id = "radioManual" })<span class="replyspan">Manual</span>
                                        @Html.RadioButton("Excel Upload", "Excel", new { @Name = "radiobutton", @value = "Excel", @text = "Excel", @id = "radiobuttonU" })<span class="replyspan">Upload File</span>
                                    </td>
                                    <td class="Validate"></td>
                                </tr>
                                <tr><td class="space"></td></tr>
                            <tr>
                                <td>@Html.Label("Car Number")<span class="required">*</span></td>
                                    <td> @Html.TextBoxFor(model => model.VehicleNumber, new { @class = "form-control", @id = "txtVehicleNumber", onkeyup = "AllowCharsNumberSymbol(this, 30)" })</td>
                                <td class="Validate">@Html.ValidationMessageFor(model => model.VehicleNumber) </td>
                            </tr>
                            <tr><td class="space"></td></tr>
                                <tr>
                                    <td>@Html.Label("Car Registration No")<span class="required">*</span></td>
                                    <td> @Html.TextBoxFor(model => model.VehicleRegNo, new { @class = "form-control", @id = "txtVehicleRegNumber", onkeyup = "AllowCharsNumberSymbol(this, 30)" })</td>
                                    <td class="Validate">@Html.ValidationMessageFor(model => model.VehicleRegNo) </td>
                                </tr>
                                <tr><td class="space"></td></tr>

                           
                                <tr>
                                <td>@Html.Label("Plate Number")@Html.Label("*", new { style = "color: red" })</td>
                                    <td>@Html.TextBoxFor(model => model.PlateNumber, new { @class = "form-control", @id = "txtPlateNumber", onkeyup = "AllowCharsNumberSymbol(this, 30)" })</td>
                                <td class="Validate"> @Html.ValidationMessageFor(model => model.PlateNumber) </td>
                            </tr>
                           <tr><td class="space"></td></tr>
                            <tr>
                                <td>@Html.Label("Fleet")<span class="required">*</span></td>
                                <td>
                                        @Html.DropDownListFor(m => m.fk_FleetID, new SelectList(Model.FleetList, "FleetID", "FleetName", Model.fk_FleetID), "--Select a Fleet--", new { @class = "form-control", @id = "ddlFleet" })
                                </td>
                                <td class="Validate"> @Html.ValidationMessageFor(model => model.fk_FleetID) </td>
                            </tr>
                            <tr><td class="space"></td></tr>
                            <tr>
                            <td>@Html.Label("Terminal")</td>
                            <td>
                                        @Html.DropDownListFor(m => m.fk_TerminalID, new SelectList(Model.TerminalList, "TerminalID", "MacAdd", Model.fk_TerminalID), "--Select a Terminal--", new { @class = "form-control", @id = "ddlTerminal" })
                            </td>
                                   
                                </tr>
                            <tr><td class="space"></td></tr>
                                <tr>
                                    <td>@Html.Label("Car Owner")</td>
                                    <td>
                                        @Html.DropDownListFor(m => m.fk_CarOwenerId, new SelectList(Model.CarOwnerList, "Id", "OwnerDetail", Model.fk_CarOwenerId), "--Select a Car owner--", new { @class = "form-control", @id = "ddlCarOwner" })
                                    </td>

                                </tr>
                                <tr><td class="space"></td></tr>
                                <tr>
                                <td>@Html.Label("Description")</td>
                                <td>
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "txtdescription", @maxlength="199"})
                                <td>
                            </tr>
                            <tr><td class="space"></td></tr>
                                <tr>
                                    <td>@Html.Label("Select a File")</td>
                                    <td>

                                        <div class="brouse-wrapper browse-btn-dt"> <input type="file" id="uploadFile" name="uploadFile" accept=".csv" placeholder="Browse a file." value="" class="filestyle" data-icon="false"></div>
                                        <a href="~/Vehicle/Download?file=CarList.csv" target="_blank">Template CSV file</a>
                                    </td>
                                    <td class="Validate"></td>
                                </tr>
                            <tr><td class="space"></td></tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><a href="Index" class="btn1">Cancel</a>&nbsp;&nbsp;&nbsp;
                                    <input type="submit" class="btnu  " value="Create" onclick="return validation();" />
                                </td>
                            </tr>
                        </table>

                    </div>
                }
            </div>

        </div>
    </div>

</div>
</body>
    

<div class="popup-block popup-ctr" id="simpleConfirm" style="display:none;width:920px;">
    <div class="mgn-B-10"><a href="/Vehicle/Index" id="close"><span class="glyphicon glyphicon-remove float-R" aria-hidden="true"></span></a></div>
    <div class="popup-form-content">
        @if (Model.IsVehicleError)
        {
            @Html.Partial("_NotUploadCarList", Model.VehicleListViewData);
        }

        <div class="row last_row butons">
            <div class="btnBox btnBox2 float_right btn-ok">
                <input type="button" value="Ok" name="Cancel" class="btn transEffects" id="btnSkip" />
            </div>
            <div class="clear"> </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function active() {
        document.getElementById("veh").className += "activeLi";
    }

    $(document).ready(function () {
        var value = $('input:radio[name=radiobutton]:checked').val();
        if (value == "Manual") {
            $("#uploadFile").attr("disabled", "disabled");

            $("#txtVehicleNumber").attr("disabled", false);
            $("#txtVehicleRegNumber").attr("disabled", false);
            $("#txtPlateNumber").attr("disabled", false);
            $("#ddlFleet").attr("disabled", false);
            $("#ddlTerminal").attr("disabled", false);
            $("#txtdescription").attr("disabled", false);
            $("#ddlCarOwner").attr("disabled", false);
            
        }
        else if (value == "Excel") {
            $("#txtVehicleNumber").attr("disabled", "disabled");
            $("#txtVehicleRegNumber").attr("disabled", "disabled");
            $("#txtPlateNumber").attr("disabled", "disabled");
            $("#ddlFleet").attr("disabled", "disabled");
            $("#ddlTerminal").attr("disabled", "disabled");
            $("#txtdescription").attr("disabled", "disabled");
            $("#ddlCarOwner").attr("disabled", "disabled");
            $("#uploadFile").attr("disabled", false);
        }
        else { }

        $("input:radio[name=radiobutton]").click(function () {
            var value = $('input:radio[name=radiobutton]:checked').val();
            if (value == "Manual") {
                $("#uploadFile").attr("disabled", "disabled");

                $("#txtVehicleNumber").attr("disabled", false);
                $("#txtVehicleRegNumber").attr("disabled", false);
                $("#txtPlateNumber").attr("disabled", false);
                $("#ddlFleet").attr("disabled", false);
                $("#ddlTerminal").attr("disabled", false);
                $("#txtdescription").attr("disabled", false);
                $("#ddlCarOwner").attr("disabled", false);
            }
            else if (value == "Excel") {
                $("#txtVehicleNumber").attr("disabled", "disabled");
                $("#txtVehicleRegNumber").attr("disabled", "disabled");
                $("#txtPlateNumber").attr("disabled", "disabled");
                $("#ddlFleet").attr("disabled", "disabled");
                $("#ddlTerminal").attr("disabled", "disabled");
                $("#txtdescription").attr("disabled", "disabled");
                $("#ddlCarOwner").attr("disabled", "disabled");
                $("#uploadFile").attr("disabled", false);

            }
            else { }
        });

    });

    function validation() {

        var response = true;
        if ($('#radiobuttonU').is(':checked')) {
            if (!$('#uploadFile').val()) {
                jAlert('Please upload excel file', 'Required Field');
                response = false;
            }
            if ($('#uploadFile').val()) {

                var fileNameExt = $('#uploadFile').val().substr($('#uploadFile').val().lastIndexOf('.') + 1);
                if (fileNameExt != "csv") {
                    jAlert('Invalid file uploaded.Please upload only csv file.', 'Required Field');
                    response = false;
                    return response;
                }

            }
        }
        if (response) {
            Showloader();
        }
        return response;
    }
</script>

MTData.Web/Views/Vehicle/Index.cshtml
@using MTD.Core.DataTransferObjects
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;
}

<head>
    <title>
        Manage Vehicle
    </title>

</head>

<body onload="active()">
    <div class="container-main">
        <div class="left-panel">
            <div class="user">
                @if (Session["User"] != null)
                {
                    var user = ((SessionDto)Session["User"]).SessionUser.FName;
                    <h3> Welcome   @user</h3>
                }
                <span class="float-R"><a href="#" id="toggle"><img src="../images/menu.png" width="34" height="21"></a></span>
            </div>
            @{

                Html.RenderAction("_MerchantUsers", "Member");
            }
        </div>


        <div class="right-panel">
            <div class="right-content">
                <div class="content-sec">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <table style="width:100%">
                            <tr>
                                <td><h4><a href="Create">Add New Car</a></h4></td>
                                <td style="float:right">

                                    <form>
                                        <div class="search-box" style="width:705px;height:45px">
                                            <input type="text" value="" name="CarOwner" id="CarOwner" placeholder="Search : Car Owner">
                                            <input type="text" value="" name="VehicleNumber" id="VehicleNumber" placeholder="Search : Car Number">
                                            <input type="text" value="" name="AndroidMac" id="AndroidMac" placeholder="Search : Android Mac Address">
                                            <span class="search-icon">
                                                <input type="submit" value="" id="LoadRecordsButton" class="search-btn" style="top:26px;position:absolute" />
                                                <input type="image" src="../images/file_extension_xls.png" alt="Export" title="Exprot to excel" style="right:45px;position:absolute" />
                                            </span>
                                            <span><input type="image" src="../images/file_extension_xls.png" alt="Export" title="Exprot to excel" /></span>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    }
                    <div id="StudentTableContainer"></div>
                    <script type="text/javascript">

                        $(document).ready(function () {

                            $('#StudentTableContainer').jtable({
                                // title: 'Payment Gateway',
                                paging: true,
                                pageSize: 15,
                                sorting: true,
                                defaultSorting: 'VehicleNumber ASC',
                                actions: {
                                    listAction: '/Vehicle/GetVehicleListByFilter',
                                    deleteAction: '/Vehicle/Delete',
                                },
                                fields: {
                                    VehicleID: {
                                        key: true,
                                        create: false,
                                        edit: false,
                                        list: false
                                    },
                                    CarOwnerName: {
                                        title: 'Car Owner',
                                        width: '14%'
                                    },
                                    VehicleNumber: {
                                        title: 'Car Number',
                                        width: '14%'
                                    },

                                    VehicleRegNo: {
                                        title: 'Car Registration No',
                                        width: '20'
                                    },
                                    PlateNumber: {
                                        title: 'Plate Number',
                                        width: '18%'
                                    },
                                    FleetName: {
                                        title: 'Fleet Name',
                                        width: '16%'
                                    },
                                    DeviceName: {
                                        title: 'Android Mac Address',
                                        sorting: false,
                                        width: '16%'

                                    },
                                    Edit: {
                                        title: 'Actions',
                                        sorting: false,
                                        width: '4%',
                                        display: function (data) {
                                            return '<a  href="Update?vehicleId=' + data.record.VehicleID + '"><img src="../Scripts/jtable/themes/metro/edit.png" title="Edit"/></a>';

                                        }
                                    },
                                }
                            });
                            //Re-load records when user click 'load records' button.
                            $('#LoadRecordsButton').click(function (e) {
                                e.preventDefault();
                                $('#StudentTableContainer').jtable('load', {
                                    name: $('#VehicleNumber').val(),
                                    carOwner: $('#CarOwner').val(),
                                    androidMac: $('#AndroidMac').val()
                                });
                            });

                            //Load all records when page is first shown
                            $('#LoadRecordsButton').click();
                        });

                    </script>
                </div>



            </div>
        </div>

    </div>
</body>

<script type="text/javascript">
    function active() {
        document.getElementById("veh").className += "activeLi";
    }
</script>